export const teamsNames = [
    "Sacramento Kings",
    "Golden State Warriors",
    "Atlanta Hawks",
    "Boston Celtics",
    "Oklahoma City Thunder",
    "Los Angeles Lakers",
    "Utah Jazz",
    "Memphis Grizzlies",
    "Milwaukee Bucks",
    "Indiana Pacers",
    "New York Knicks",
    "Denver Nuggets",
    "Minnesota Timberwolves",
    "Philadelphia 76ers",
    "New Orleans Pelicans",
    "Dallas Mavericks",
    "Phoenix Suns",
    "Los Angeles Clippers",
    "Portland Trail Blazers",
    "Brooklyn Nets",
    "Washington Wizards",
    "Chicago Bulls",
    "San Antonio Spurs",
    "Toronto Raptors",
    "Cleveland Cavaliers",
    "Orlando Magic",
    "Charlotte Hornets",
    "Houston Rockets",
    "Detroit Pistons",
    "Miami Heat"
]