package models

type TotalTeamData struct {
	TeamName string           `json:"teamname,omitempty" validate:"required"`
	Stats    []YearlyTeamData `json:"Stats,omitempty" validate:"required"`
}

type YearlyTeamData struct {
	Year      string   `json:"year,omitempty" validate:"required"`
	YearStats TeamData `json:"yearstats,omitempty" validate:"required"`
}

type TeamData struct {
	ID               string  `json:"_id,omitempty" validate:"required"`
	G                float64 `json:"g,omitempty" validate:"required"`
	MP               float64 `json:"mp,omitempty" validate:"required"`
	FG               float64 `json:"fg,omitempty" validate:"required"`
	FGA              float64 `json:"fga,omitempty" validate:"required"`
	FGPct            float64 `json:"fg_pct,omitempty" validate:"required"`
	FG3              float64 `json:"fg3,omitempty" validate:"required"`
	FG3A             float64 `json:"fg3a,omitempty" validate:"required"`
	FG3Pct           float64 `json:"fg3_pct,omitempty" validate:"required"`
	FG2              float64 `json:"fg2,omitempty" validate:"required"`
	FG2A             float64 `json:"fg2a,omitempty" validate:"required"`
	FG2Pct           float64 `json:"fg2_pct,omitempty" validate:"required"`
	FT               float64 `json:"ft,omitempty" validate:"required"`
	FTA              float64 `json:"fta,omitempty" validate:"required"`
	FTPct            float64 `json:"ft_pct,omitempty" validate:"required"`
	ORB              float64 `json:"orb,omitempty" validate:"required"`
	DRB              float64 `json:"drb,omitempty" validate:"required"`
	TRB              float64 `json:"trb,omitempty" validate:"required"`
	AST              float64 `json:"ast,omitempty" validate:"required"`
	STL              float64 `json:"stl,omitempty" validate:"required"`
	BLK              float64 `json:"blk,omitempty" validate:"required"`
	TOV              float64 `json:"tov,omitempty" validate:"required"`
	PF               float64 `json:"pf,omitempty" validate:"required"`
	PTS              float64 `json:"pts,omitempty" validate:"required"`
	OppFG            float64 `json:"opp_fg,omitempty" validate:"required"`
	OppFGA           float64 `json:"opp_fga,omitempty" validate:"required"`
	OppFGPct         float64 `json:"opp_fg_pct,omitempty" validate:"required"`
	OppFG3           float64 `json:"opp_fg3,omitempty" validate:"required"`
	OppFG3A          float64 `json:"opp_fg3a,omitempty" validate:"required"`
	OppFG3Pct        float64 `json:"opp_fg3_pct,omitempty" validate:"required"`
	OppFG2           float64 `json:"opp_fg2,omitempty" validate:"required"`
	OppFG2A          float64 `json:"opp_fg2a,omitempty" validate:"required"`
	OppFG2Pct        float64 `json:"opp_fg2_pct,omitempty" validate:"required"`
	OppFT            float64 `json:"opp_ft,omitempty" validate:"required"`
	OppFTA           float64 `json:"opp_fta,omitempty" validate:"required"`
	OppFTPct         float64 `json:"opp_ft_pct,omitempty" validate:"required"`
	OppORB           float64 `json:"opp_orb,omitempty" validate:"required"`
	OppDRB           float64 `json:"opp_drb,omitempty" validate:"required"`
	OppTRB           float64 `json:"opp_trb,omitempty" validate:"required"`
	OppAST           float64 `json:"opp_ast,omitempty" validate:"required"`
	OppSTL           float64 `json:"opp_stl,omitempty" validate:"required"`
	OppBLK           float64 `json:"opp_blk,omitempty" validate:"required"`
	OppTOV           float64 `json:"opp_tov,omitempty" validate:"required"`
	OppPF            float64 `json:"opp_pf,omitempty" validate:"required"`
	OppPTS           float64 `json:"opp_pts,omitempty" validate:"required"`
	Age              float64 `json:"age,omitempty" validate:"required"`
	Wins             float64 `json:"wins,omitempty" validate:"required"`
	Losses           float64 `json:"losses,omitempty" validate:"required"`
	WinsPyth         float64 `json:"wins_pyth,omitempty" validate:"required"`
	LossesPyth       float64 `json:"losses_pyth,omitempty" validate:"required"`
	MOV              float64 `json:"mov,omitempty" validate:"required"`
	SOS              float64 `json:"sos,omitempty" validate:"required"`
	SRS              float64 `json:"srs,omitempty" validate:"required"`
	OffRtg           float64 `json:"off_rtg,omitempty" validate:"required"`
	DefRtg           float64 `json:"def_rtg,omitempty" validate:"required"`
	NetRtg           float64 `json:"net_rtg,omitempty" validate:"required"`
	Pace             float64 `json:"pace,omitempty" validate:"required"`
	FTAPerFGAPct     float64 `json:"fta_per_fga_pct,omitempty" validate:"required"`
	FG3APerFGAPct    float64 `json:"fg3a_per_fga_pct,omitempty" validate:"required"`
	TSPct            float64 `json:"ts_pct,omitempty" validate:"required"`
	EFGPct           float64 `json:"efg_pct,omitempty" validate:"required"`
	TOVPct           float64 `json:"tov_pct,omitempty" validate:"required"`
	ORBPct           float64 `json:"orb_pct,omitempty" validate:"required"`
	FTRate           float64 `json:"ft_rate,omitempty" validate:"required"`
	OppEFGPct        float64 `json:"opp_efg_pct,omitempty" validate:"required"`
	OppTOVPct        float64 `json:"opp_tov_pct,omitempty" validate:"required"`
	DRBPct           float64 `json:"drb_pct,omitempty" validate:"required"`
	OppFTRate        float64 `json:"opp_ft_rate,omitempty" validate:"required"`
	AvgDist          float64 `json:"avg_dist,omitempty" validate:"required"`
	PctFGA2A         float64 `json:"pct_fga_fg2a,omitempty" validate:"required"`
	PctFGA003        float64 `json:"pct_fga_00_03,omitempty" validate:"required"`
	PctFGA0310       float64 `json:"pct_fga_03_10,omitempty" validate:"required"`
	PctFGA1016       float64 `json:"pct_fga_10_16,omitempty" validate:"required"`
	PctFGA16XX       float64 `json:"pct_fga_16_xx,omitempty" validate:"required"`
	PctFGA3A         float64 `json:"pct_fga_fg3a,omitempty" validate:"required"`
	FGPct003         float64 `json:"fg_pct_00_03,omitempty" validate:"required"`
	FGPct0310        float64 `json:"fg_pct_03_10,omitempty" validate:"required"`
	FGPct1016        float64 `json:"fg_pct_10_16,omitempty" validate:"required"`
	FGPct16XX        float64 `json:"fg_pct_16_xx,omitempty" validate:"required"`
	PctASTFG2        float64 `json:"pct_ast_fg2,omitempty" validate:"required"`
	PctASTFG3        float64 `json:"pct_ast_fg3,omitempty" validate:"required"`
	PctFGADunk       float64 `json:"pct_fga_dunk,omitempty" validate:"required"`
	FGDunk           float64 `json:"fg_dunk,omitempty" validate:"required"`
	PctFGALayup      float64 `json:"pct_fga_layup,omitempty" validate:"required"`
	FGLayup          float64 `json:"fg_layup,omitempty" validate:"required"`
	PctFG3ACorner    float64 `json:"pct_fg3a_corner,omitempty" validate:"required"`
	FG3PctCorner     float64 `json:"fg3_pct_corner,omitempty" validate:"required"`
	OppAvgDist       float64 `json:"opp_avg_dist,omitempty" validate:"required"`
	OppPctFGA2A      float64 `json:"opp_pct_fga_fg2a,omitempty" validate:"required"`
	OppPctFGA003     float64 `json:"opp_pct_fga_00_03,omitempty" validate:"required"`
	OppPctFGA0310    float64 `json:"opp_pct_fga_03_10,omitempty" validate:"required"`
	OppPctFGA1016    float64 `json:"opp_pct_fga_10_16,omitempty" validate:"required"`
	OppPctFGA16XX    float64 `json:"opp_pct_fga_16_xx,omitempty" validate:"required"`
	OppPctFGA3A      float64 `json:"opp_pct_fga_fg3a,omitempty" validate:"required"`
	OppFGPct003      float64 `json:"opp_fg_pct_00_03,omitempty" validate:"required"`
	OppFGPct0310     float64 `json:"opp_fg_pct_03_10,omitempty" validate:"required"`
	OppFGPct1016     float64 `json:"opp_fg_pct_10_16,omitempty" validate:"required"`
	OppFGPct16XX     float64 `json:"opp_fg_pct_16_xx,omitempty" validate:"required"`
	OppPctASTFG2     float64 `json:"opp_pct_ast_fg2,omitempty" validate:"required"`
	OppPctASTFG3     float64 `json:"opp_pct_ast_fg3,omitempty" validate:"required"`
	OppPctFGADunk    float64 `json:"opp_pct_fga_dunk,omitempty" validate:"required"`
	OppFGDunk        float64 `json:"opp_fg_dunk,omitempty" validate:"required"`
	OppPctFGALayup   float64 `json:"opp_pct_fga_layup,omitempty" validate:"required"`
	OppFGLayup       float64 `json:"opp_fg_layup,omitempty" validate:"required"`
	OppPctFG3ACorner float64 `json:"opp_pct_fg3a_corner,omitempty" validate:"required"`
	OppFG3PctCorner  float64 `json:"opp_fg3_pct_corner,omitempty" validate:"required"`
}
