# Generated by Django 5.0.4 on 2024-05-08 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LR_pred',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FGM', models.DecimalField(decimal_places=5, max_digits=8)),
                ('FGpercent', models.DecimalField(decimal_places=5, max_digits=8)),
                ('threeMade', models.DecimalField(decimal_places=5, max_digits=8)),
                ('FTM', models.DecimalField(decimal_places=5, max_digits=8)),
                ('ftpercent', models.DecimalField(decimal_places=5, max_digits=8)),
                ('DREB', models.DecimalField(decimal_places=5, max_digits=8)),
                ('OREB', models.DecimalField(decimal_places=5, max_digits=8)),
                ('AST', models.DecimalField(decimal_places=5, max_digits=8)),
                ('STL', models.DecimalField(decimal_places=5, max_digits=8)),
                ('BLK', models.DecimalField(decimal_places=5, max_digits=8)),
                ('TOV', models.DecimalField(decimal_places=5, max_digits=8)),
                ('PF', models.DecimalField(decimal_places=5, max_digits=8)),
            ],
        ),
    ]
