// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.2
// source: teams.proto

package TeamsProto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TwoTeamsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Team1 string `protobuf:"bytes,1,opt,name=team1,proto3" json:"team1,omitempty"`
	Team2 string `protobuf:"bytes,2,opt,name=team2,proto3" json:"team2,omitempty"`
	Year  int32  `protobuf:"varint,3,opt,name=year,proto3" json:"year,omitempty"`
}

func (x *TwoTeamsRequest) Reset() {
	*x = TwoTeamsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_teams_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TwoTeamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TwoTeamsRequest) ProtoMessage() {}

func (x *TwoTeamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_teams_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TwoTeamsRequest.ProtoReflect.Descriptor instead.
func (*TwoTeamsRequest) Descriptor() ([]byte, []int) {
	return file_teams_proto_rawDescGZIP(), []int{0}
}

func (x *TwoTeamsRequest) GetTeam1() string {
	if x != nil {
		return x.Team1
	}
	return ""
}

func (x *TwoTeamsRequest) GetTeam2() string {
	if x != nil {
		return x.Team2
	}
	return ""
}

func (x *TwoTeamsRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

type TwoTeamsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Team1 *Team `protobuf:"bytes,1,opt,name=team1,proto3" json:"team1,omitempty"`
	Team2 *Team `protobuf:"bytes,2,opt,name=team2,proto3" json:"team2,omitempty"`
}

func (x *TwoTeamsResponse) Reset() {
	*x = TwoTeamsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_teams_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TwoTeamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TwoTeamsResponse) ProtoMessage() {}

func (x *TwoTeamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_teams_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TwoTeamsResponse.ProtoReflect.Descriptor instead.
func (*TwoTeamsResponse) Descriptor() ([]byte, []int) {
	return file_teams_proto_rawDescGZIP(), []int{1}
}

func (x *TwoTeamsResponse) GetTeam1() *Team {
	if x != nil {
		return x.Team1
	}
	return nil
}

func (x *TwoTeamsResponse) GetTeam2() *Team {
	if x != nil {
		return x.Team2
	}
	return nil
}

type Team struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Test  string `protobuf:"bytes,1,opt,name=test,proto3" json:"test,omitempty"`
	Works int32  `protobuf:"varint,2,opt,name=works,proto3" json:"works,omitempty"`
}

func (x *Team) Reset() {
	*x = Team{}
	if protoimpl.UnsafeEnabled {
		mi := &file_teams_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Team) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Team) ProtoMessage() {}

func (x *Team) ProtoReflect() protoreflect.Message {
	mi := &file_teams_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Team.ProtoReflect.Descriptor instead.
func (*Team) Descriptor() ([]byte, []int) {
	return file_teams_proto_rawDescGZIP(), []int{2}
}

func (x *Team) GetTest() string {
	if x != nil {
		return x.Test
	}
	return ""
}

func (x *Team) GetWorks() int32 {
	if x != nil {
		return x.Works
	}
	return 0
}

var File_teams_proto protoreflect.FileDescriptor

var file_teams_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x74, 0x65, 0x61, 0x6d, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x74,
	0x65, 0x61, 0x6d, 0x73, 0x22, 0x51, 0x0a, 0x0f, 0x54, 0x77, 0x6f, 0x54, 0x65, 0x61, 0x6d, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x65, 0x61, 0x6d, 0x31,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x65, 0x61, 0x6d, 0x31, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x65, 0x61, 0x6d, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x65,
	0x61, 0x6d, 0x32, 0x12, 0x12, 0x0a, 0x04, 0x79, 0x65, 0x61, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x79, 0x65, 0x61, 0x72, 0x22, 0x58, 0x0a, 0x10, 0x54, 0x77, 0x6f, 0x54, 0x65,
	0x61, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x05, 0x74,
	0x65, 0x61, 0x6d, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x74, 0x65, 0x61,
	0x6d, 0x73, 0x2e, 0x54, 0x65, 0x61, 0x6d, 0x52, 0x05, 0x74, 0x65, 0x61, 0x6d, 0x31, 0x12, 0x21,
	0x0a, 0x05, 0x74, 0x65, 0x61, 0x6d, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e,
	0x74, 0x65, 0x61, 0x6d, 0x73, 0x2e, 0x54, 0x65, 0x61, 0x6d, 0x52, 0x05, 0x74, 0x65, 0x61, 0x6d,
	0x32, 0x22, 0x30, 0x0a, 0x04, 0x54, 0x65, 0x61, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x73,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x77, 0x6f,
	0x72, 0x6b, 0x73, 0x32, 0x4e, 0x0a, 0x0c, 0x54, 0x65, 0x61, 0x6d, 0x73, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x3e, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x54, 0x77, 0x6f, 0x54, 0x65, 0x61,
	0x6d, 0x73, 0x12, 0x16, 0x2e, 0x74, 0x65, 0x61, 0x6d, 0x73, 0x2e, 0x54, 0x77, 0x6f, 0x54, 0x65,
	0x61, 0x6d, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x74, 0x65, 0x61,
	0x6d, 0x73, 0x2e, 0x54, 0x77, 0x6f, 0x54, 0x65, 0x61, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x0f, 0x5a, 0x0d, 0x2e, 0x2e, 0x2f, 0x54, 0x65, 0x61, 0x6d, 0x73, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_teams_proto_rawDescOnce sync.Once
	file_teams_proto_rawDescData = file_teams_proto_rawDesc
)

func file_teams_proto_rawDescGZIP() []byte {
	file_teams_proto_rawDescOnce.Do(func() {
		file_teams_proto_rawDescData = protoimpl.X.CompressGZIP(file_teams_proto_rawDescData)
	})
	return file_teams_proto_rawDescData
}

var file_teams_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_teams_proto_goTypes = []any{
	(*TwoTeamsRequest)(nil),  // 0: teams.TwoTeamsRequest
	(*TwoTeamsResponse)(nil), // 1: teams.TwoTeamsResponse
	(*Team)(nil),             // 2: teams.Team
}
var file_teams_proto_depIdxs = []int32{
	2, // 0: teams.TwoTeamsResponse.team1:type_name -> teams.Team
	2, // 1: teams.TwoTeamsResponse.team2:type_name -> teams.Team
	0, // 2: teams.TeamsService.GetTwoTeams:input_type -> teams.TwoTeamsRequest
	1, // 3: teams.TeamsService.GetTwoTeams:output_type -> teams.TwoTeamsResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_teams_proto_init() }
func file_teams_proto_init() {
	if File_teams_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_teams_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*TwoTeamsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_teams_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*TwoTeamsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_teams_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*Team); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_teams_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_teams_proto_goTypes,
		DependencyIndexes: file_teams_proto_depIdxs,
		MessageInfos:      file_teams_proto_msgTypes,
	}.Build()
	File_teams_proto = out.File
	file_teams_proto_rawDesc = nil
	file_teams_proto_goTypes = nil
	file_teams_proto_depIdxs = nil
}
