version: '3.8'

services:
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    env_file:
      - ./api-gateway/.env
    ports:
      - "8080:8080"
    depends_on:
      - teamsservice
      - predictionservice
    networks:
      - microservices-network

  teamsservice:
    build: ./teamsservice
    container_name: teamsservice
    env_file:
      - ./teamsservice/.env
    ports:
      - "50051:50051"
    networks:
      - microservices-network

  predictionservice:
    build: ./predictions
    container_name: predictionservice
    env_file:
      - ./predictions/.env
    ports:
      - "50052:50052"
    depends_on:
      - redis
    networks:
      - microservices-network
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - microservices-network

networks:
  microservices-network: