version: '3.8'

services:
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - teamsservice
      - predictionservice
    networks:
      - microservices-network
    environment:
      - TEAMS_SERVICE=teamsservice:50051
      - PREDICTION_SERVICE=predictionservice:50052
      - REDIS=redis:6379

  teamsservice:
    build: ./teamsservice
    container_name: teamsservice
    ports:
      - "50051:50051"
    networks:
      - microservices-network

  predictionservice:
    build: ./predictions
    container_name: predictionservice
    ports:
      - "50052:50052"
    depends_on:
      - redis
    networks:
      - microservices-network
    environment:
      - TEAMS_SERVICE=teamsservice:50051

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - microservices-network

networks:
  microservices-network: