package constants

const (
	REDIS_TWOTEAMS         = "API_GATEWAY_TWOTEAMS_"
	REDIS_TWOTEAMS_ORDERED = "API_GATEWAY_TWOTEAMSORDERED_"
	REDIS_ALLTEAMS         = "API_GATEWAY_ALLTEAMS_"
	REDIS_PREDICTION       = "API_GATEWAY_PREDICTION_"
)